export declare function logAuditAction(userEmail: string, action: string, ipAddress: string, details?: string): void;
export declare function addEventOperator(eventId: string, name: string, passwordHash: string, accessToken: string): string;
export declare function listEventOperators(eventId: string): {
    id: string;
    event_id: string;
    name: string;
    access_token: string;
    created_at: string;
}[];
export declare function getEventOperatorByToken(token: string): {
    id: string;
    event_id: string;
    name: string;
    password_hash: string;
    access_token: string;
    created_at: string;
} | undefined;
export declare function deleteEventOperator(id: string, eventId: string): void;
export declare function createEvent(name: string, date: string, description: string, settings?: {
    photoCount?: number;
    countdown?: number;
    captureInterval?: number;
    postCapturePreview?: number;
    dslrIso?: string;
    dslrShutterSpeed?: string;
    dslrAperture?: string;
    dslrFocusMode?: string;
    dslrWhiteBalance?: string;
    dslrWhiteBalanceKelvin?: number;
    obfuscateLinks?: number;
    expiryType?: string;
    expiryValue?: string;
    organizer?: string;
    contactInfo?: string;
}): {
    id: string;
    otp: string;
};
export declare function updateEventById(id: string, name: string, date: string, description: string, settings?: {
    photoCount?: number;
    countdown?: number;
    captureInterval?: number;
    postCapturePreview?: number;
    dslrIso?: string;
    dslrShutterSpeed?: string;
    dslrAperture?: string;
    dslrFocusMode?: string;
    dslrWhiteBalance?: string;
    dslrWhiteBalanceKelvin?: number;
    obfuscateLinks?: number;
    expiryType?: string;
    expiryValue?: string;
    organizer?: string;
    contactInfo?: string;
}): void;
export declare function updateEventSettingsById(id: string, settings: {
    photoCount: number;
    countdown: number;
    captureInterval: number;
    postCapturePreview: number;
    dslrIso: string;
    dslrShutterSpeed: string;
    dslrAperture: string;
    dslrFocusMode?: string;
    dslrWhiteBalance?: string;
    dslrWhiteBalanceKelvin?: number;
    obfuscateLinks?: number;
    expiryType?: string;
    expiryValue?: string;
    organizer?: string;
    contactInfo?: string;
}): void;
export declare function getEvent(id: string): {
    id: string;
    name: string;
    date: string;
    description: string;
    otp: string;
    status: string;
    photo_count: number;
    countdown: number;
    capture_interval: number;
    post_capture_preview: number;
    dslr_iso: string;
    dslr_shutterspeed: string;
    dslr_aperture: string;
    dslr_focus_mode: string;
    dslr_whitebalance: string;
    dslr_whitebalance_kelvin: number;
    obfuscate_links: number;
    expiry_type: string;
    expiry_value: string;
    organizer: string;
    contact_info: string;
    operator_password?: string;
    created_at: string;
} | undefined;
export declare function getEventByOtp(otp: string): {
    id: string;
    name: string;
    date: string;
    description: string;
    otp: string;
    status: string;
    photo_count: number;
    countdown: number;
    capture_interval: number;
    post_capture_preview: number;
    dslr_iso: string;
    dslr_shutterspeed: string;
    dslr_aperture: string;
    dslr_focus_mode: string;
    dslr_whitebalance: string;
    dslr_whitebalance_kelvin: number;
    obfuscate_links: number;
    expiry_type: string;
    expiry_value: string;
    organizer: string;
    contact_info: string;
    created_at: string;
    share_originals: number;
} | undefined;
export declare function listEvents(includeEnded?: boolean): Array<{
    id: string;
    name: string;
    date: string;
    description: string;
    otp: string;
    status: string;
    photo_count: number;
    countdown: number;
    capture_interval: number;
    post_capture_preview: number;
    dslr_iso: string;
    dslr_shutterspeed: string;
    dslr_aperture: string;
    dslr_focus_mode: string;
    dslr_whitebalance: string;
    dslr_whitebalance_kelvin: number;
    obfuscate_links: number;
    expiry_type: string;
    expiry_value: string;
    organizer: string;
    contact_info: string;
    created_at: string;
    share_originals: number;
}>;
export declare function endEvent(id: string): void;
export declare function deleteEvent(id: string): void;
export declare function ensurePhotoSession(sessionId: string, eventId: string): string;
export declare function reservePhotoSession(sessionId: string, eventId: string): string;
export declare function updateUploadStatus(sessionId: string, status: 'reserved' | 'uploading' | 'complete' | 'failed', extra?: {
    upload_started_at?: number;
    upload_completed_at?: number;
    upload_size_bytes?: number;
    upload_avg_speed_kbps?: number;
}): void;
export declare function setSessionDimensions(sessionId: string, width: number, height: number): void;
export declare function getSessionDimensions(sessionId: string): {
    width: number;
    height: number;
};
export declare function getSessionUploadStatus(token: string): {
    id: string;
    upload_status: string;
    upload_started_at: number | null;
    upload_completed_at: number | null;
    upload_size_bytes: number | null;
    upload_avg_speed_kbps: number | null;
    share_id: string;
} | null;
export declare function getPhotoSession(sessionId: string): {
    id: string;
    event_id: string;
    created_at: string;
} | undefined;
export declare function listEventPhotoSessions(eventId: string, includeArchived?: boolean): Array<{
    id: string;
    event_id: string;
    created_at: string;
    archived: number;
    share_id: string;
    width: number;
    height: number;
}>;
export declare function archiveSession(sessionId: string): void;
export declare function restoreSession(sessionId: string): void;
export declare function getGlobalSettings(): {
    photoCount: any;
    countdown: any;
    captureInterval: any;
    postCapturePreview: any;
    dslrIso: any;
    dslrShutterSpeed: any;
    dslrAperture: any;
    dslrFocusMode: any;
    dslrWhiteBalance: any;
    dslrWhiteBalanceKelvin: any;
    organizer: any;
    contactInfo: any;
    apiRateLimitAdmin: any;
    apiRateLimitShare: any;
    bwLimitAdmin: any;
    bwLimitShare: any;
    lockoutDuration: any;
};
export declare function updateGlobalSettings(settings: {
    photoCount: number;
    countdown: number;
    captureInterval: number;
    postCapturePreview: number;
    dslrIso: string;
    dslrShutterSpeed: string;
    dslrAperture: string;
    dslrFocusMode?: string;
    dslrWhiteBalance?: string;
    dslrWhiteBalanceKelvin?: number;
    organizer?: string;
    contactInfo?: string;
    apiRateLimitAdmin?: number;
    apiRateLimitShare?: number;
    bwLimitAdmin?: number;
    bwLimitShare?: number;
    lockoutDuration?: number;
}): void;
export declare function getCameraSettings(model: string): {
    dslrIso: string;
    dslrShutterSpeed: string;
    dslrAperture: string;
    dslrFocusMode: string;
    dslrWhiteBalance: string;
    dslrWhiteBalanceKelvin: number;
} | null;
export declare function updateCameraSettings(model: string, settings: {
    dslrIso: string;
    dslrShutterSpeed: string;
    dslrAperture: string;
    dslrFocusMode?: string;
    dslrWhiteBalance?: string;
    dslrWhiteBalanceKelvin?: number;
    organizer?: string;
    contactInfo?: string;
}): void;
export declare function closeDb(): void;
export declare function regenerateSessionShareId(sessionId: string): string;
export declare function createSessionShare(sessionId: string): string;
export declare function getSessionShares(sessionId: string): Array<{
    id: string;
    session_id: string;
    is_active: number;
    created_at: string;
}>;
export declare function setSessionShareStatus(shareId: string, isActive: boolean): void;
export declare function deleteSessionShare(shareId: string): void;
export declare function getPhotoSessionByShareId(shareId: string): {
    id: string;
    event_id: string;
    created_at: string;
    share_id: string;
    archived: number;
} | undefined;
export declare function logShareAnalytics(shareId: string, ipAddress: string | null, deviceType: string | null, os: string | null, browser: string | null, action: string, targetFile?: string | null, source?: string | null): void;
export declare function getEventAnalytics(eventId: string): {
    totalVisits: number;
    uniqueVisitors: number;
    logs: unknown[];
};
export declare function findUserByEmail(email: string): any;
export declare function insertUser(id: string, email: string, passwordHash: string, role: string): void;
export declare function getAllUsers(): unknown[];
export declare function deleteUser(id: string): void;
export declare function countUsers(): any;
export declare function updateUserRole(id: string, role: string): void;
export declare function setEventShareOriginals(id: string, value: number): void;
export declare function getOrCreateEventShareToken(eventId: string): string;
export declare function getEventIdByShareToken(token: string): string | null;
export declare function parseMessageTextarea(raw: string): string[];
export declare function resolveMessages(event: any, globals: any, slot: 'homepage' | 'countdown' | 'post_session' | 'share_title'): string[];
export declare function getGlobalMessages(): {
    msgHomepage: any;
    msgCountdown: any;
    msgPostSession: any;
    msgShareTitle: any;
    msgOrder: any;
};
export declare function updateGlobalMessages(msgs: {
    msgHomepage: string | null;
    msgCountdown: string | null;
    msgPostSession: string | null;
    msgShareTitle: string | null;
    msgOrder: string;
}): void;
export declare function updateEventMessages(eventId: string, msgs: {
    msgHomepage: string | null;
    msgCountdown: string | null;
    msgPostSession: string | null;
    msgShareTitle: string | null;
    msgOrder: string;
}): void;
export declare function updateSessionShareTitle(sessionId: string, shareTitle: string): void;
